CREATE TABLE [dbo].[VF_API_CATALOG_CLIENTS] (
    [TRANSDEV_ID]   INT              IDENTITY (1, 1) NOT NULL,
    [CLIENT_ID]     UNIQUEIDENTIFIER NULL,
    [CLIENT_NAME]   VARCHAR (250)    NULL,
    [CLIENT_TOKEN]  VARCHAR (250)    NULL,
    [CLIENT_STATUS] BIT              NULL,
    CONSTRAINT [PK_VF_API_CATALOG_CLIENTS] PRIMARY KEY CLUSTERED ([TRANSDEV_ID] ASC)
);

