CREATE TABLE [dbo].[VF_API_CLIENT_OBJECTS] (
    [CLIENT_OBJECT_ID]        UNIQUEIDENTIFIER NOT NULL,
    [TRANSDEV_ID]             INT              NOT NULL,
    [TRANSDEV_PARAM]          VARCHAR (50)     NOT NULL,
    [DATA_PROVIDER_ID]        INT              NOT NULL,
    [DB_SERVER_NAME]          VARCHAR (250)    NULL,
    [DB_SERVER_PORT]          VARCHAR (50)     NULL,
    [DB_NAME]                 VARCHAR (250)    NULL,
    [DB_USER]                 VARCHAR (250)    NULL,
    [DB_USER_PASSWORD]        VARCHAR (250)    NULL,
    [DB_INTEGRATED_SECURITY]  BIT              NULL,
    [DB_SCHEMA]               VARCHAR (250)    NULL,
    [DB_OBJECT_NAME]          VARCHAR (250)    NULL,
    [DB_OBJECT_CREATED_DATE]  DATETIME         NOT NULL,
    [DB_OBJECT_MODIFIED_DATE] DATETIME         NOT NULL,
    CONSTRAINT [PK_VF_API_CLIENT_OBJECTS_1] PRIMARY KEY CLUSTERED ([CLIENT_OBJECT_ID] ASC),
    CONSTRAINT [FK_VF_API_CLIENT_OBJECTS_VF_API_CATALOG_CLIENTS] FOREIGN KEY ([TRANSDEV_ID]) REFERENCES [dbo].[VF_API_CATALOG_CLIENTS] ([TRANSDEV_ID]),
    CONSTRAINT [FK_VF_API_CLIENT_OBJECTS_VF_DATA_PROVIDER] FOREIGN KEY ([DATA_PROVIDER_ID]) REFERENCES [dbo].[VF_DATA_PROVIDER] ([DATA_PROVIDER_ID])
);













