CREATE TABLE [dbo].[VF_DATA_PROVIDER] (
    [DATA_PROVIDER_ID]   INT           NOT NULL,
    [DATA_PROVIDER_Name] VARCHAR (350) NOT NULL,
    CONSTRAINT [PK_VF_DATA_PRVIDER] PRIMARY KEY CLUSTERED ([DATA_PROVIDER_ID] ASC)
);





