CREATE TABLE [dbo].[VF_DATA_PROVIDER] (
    [DATA_PROVIDER_ID]   INT           NOT NULL,
    [DATA_PROVIDER_Name] VARCHAR (350) NOT NULL,
    CONSTRAINT [PK_VF_DATA_PRVIDER] PRIMARY KEY CLUSTERED ([DATA_PROVIDER_ID] ASC),
    CONSTRAINT [FK_VF_DATA_PROVIDER_VF_DATA_PROVIDER] FOREIGN KEY ([DATA_PROVIDER_ID]) REFERENCES [dbo].[VF_DATA_PROVIDER] ([DATA_PROVIDER_ID])
);



