//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalFew.Transdev.Australasia.Data.Core.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VF_API_CATALOG_CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VF_API_CATALOG_CLIENTS()
        {
            this.VF_API_CLIENT_OBJECTS = new HashSet<VF_API_CLIENT_OBJECTS>();
        }
    
        public int TRANSDEV_ID { get; set; }
        public System.Guid CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_TOKEN { get; set; }
        public bool CLIENT_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VF_API_CLIENT_OBJECTS> VF_API_CLIENT_OBJECTS { get; set; }
    }
}
