//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalFew.Transdev.Australasia.Data.Core.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class VF_API_CLIENT_OBJECTS
    {
        public System.Guid CLIENT_OBJECT_ID { get; set; }
        public int TRANSDEV_ID { get; set; }
        public string TRANSDEV_PARAM { get; set; }

        [DisplayName("Data Provider")]
        [Required]
        public int DATA_PROVIDER_ID { get; set; }

        [DisplayName("Server Name")]
        [Required]
        public string DB_SERVER_NAME { get; set; }

        [DisplayName("Server Port")]
        public string DB_SERVER_PORT { get; set; }

        [DisplayName("Database NAME")]
        public string DB_NAME { get; set; }

        [DisplayName("Database User")]
        public string DB_USER { get; set; }

        [DisplayName("Database User Password")]
        public string DB_USER_PASSWORD { get; set; }

        [DisplayName("Integrated Security")]
        public Nullable<bool> DB_INTEGRATED_SECURITY { get; set; }
        public string DB_SCHEMA { get; set; }
        public string DB_OBJECT_NAME { get; set; }
        public System.DateTime DB_OBJECT_CREATED_DATE { get; set; }
        public System.DateTime DB_OBJECT_MODIFIED_DATE { get; set; }
    
        public virtual VF_API_CATALOG_CLIENTS VF_API_CATALOG_CLIENTS { get; set; }
        public virtual VF_DATA_PROVIDER VF_DATA_PROVIDER { get; set; }
    }
}
