//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalFew.Transdev.Australasia.Data.Core.Database
{

    public partial class VF_DATA_PROVIDER
    {
        public int DATA_PROVIDER_ID { get; set; }
        public string DATA_PROVIDER_Name { get; set; }
    }
}
