//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitalFew.Transdev.Australasia.Data.Api.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VF_API_CLIENT_OBJECTS
    {
        public int TRANSDEV_ID { get; set; }
        public string TRANSDEV_PARAM { get; set; }
        public string DB_SERVER_NAME { get; set; }
        public string DB_INSTANCE_NAME { get; set; }
        public string DB_SERVER_PORT { get; set; }
        public string DB_NAME { get; set; }
        public string DB_USER { get; set; }
        public string DB_USER_PASSWORD { get; set; }
        public string DB_AUTHENTICATION_TYPE { get; set; }
        public Nullable<bool> DB_INTEGRATED_SECURITY { get; set; }
        public int OBJECT_ID { get; set; }
        public string DB_SCHEMA { get; set; }
        public string DB_OBJECT_TYPE { get; set; }
        public string DB_OBJECT_NAME { get; set; }
        public Nullable<System.DateTime> DB_OBJECT_CREATED_DATE { get; set; }
        public Nullable<System.DateTime> DB_OBJECT_MODIFIED_DATE { get; set; }
    
        public virtual VF_API_CATALOG_CLIENTS VF_API_CATALOG_CLIENTS { get; set; }
    }
}
